# Data
data_dir: "/p/project1/hai_1127/inputs/processed_data/training_dataset1.nc"
variables: ["to", "zos", "mld", "land_mask", "target"]

# Model
in_channels: 4
out_channels: 1

# Training
batch_size: 32
learning_rate: 0.001
max_epochs: 1000
num_workers: 2
seed: 42
output_dir: "outputs" 
loss_fn: "BCEWithLogitsLoss"

# Features
add_temporal_features: true
normalize: true

# Data splits
train_ratio: 0.85
val_ratio: 0.1
test_ratio: 0.05